<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\EventoController;
use App\Http\Controllers\Api\PersonaController;
use App\Http\Controllers\Api\EquipoController;
use App\Http\Controllers\Api\AuspiciadorController;
use App\Http\Controllers\Api\RolPersonaController;
use App\Http\Controllers\Api\InstitucionController;
use App\Http\Controllers\Api\DisponibilidadController;
use App\Http\Controllers\Api\EtapaController;
use App\Http\Controllers\Api\UbicacionController;
use App\Http\Controllers\Api\CodigosVerificacionController;
use App\Http\Controllers\Api\TipoEventoController;
use App\Http\Controllers\Api\InscripcionController;
use App\Http\Controllers\Api\UsuarioController;
use App\Http\Controllers\Api\RolesController;

Route::middleware(['auth:api', 'check_tarea'])->group(function () {
    Route::get('eventos',[EventoController::class, 'index'])->name('eventos');
    Route::post('validar-evento',[EventoController::class, 'validarFormulario'])->name('validar-evento');
    Route::post('guardar-evento',[EventoController::class, 'guardarEvento'])->name('guardar-evento');
    Route::get('evento/{id}',[EventoController::class, 'show'])->name('evento.show');
    Route::put('evento/{id}',[EventoController::class, 'update'])->name('evento.update');
    Route::get('eventos-no-mostrar', [EventoController::class, 'getEventosNoMostrar'])->name('eventos-no-mostrar');
    Route::delete('quitar-evento/{id}', [EventoController::class, 'QuitarEvento'])->name('quitar-evento');
    Route::get('actualizar-estado',[EventoController::class, 'actualizarEstadoTodos'])->name('actualizar-estado');
    Route::get('eventos-modificables', [EventoController::class, 'getEventosEnEspera'])->name('eventos-modificables');
    Route::get('lista-equipos',[EquipoController::class, 'listaEquipos'])->name('lista-equipos');
    Route::get('lista-organizadores',[RolPersonaController::class, 'listaOrganizadores'])->name('lista-organizadores');
    Route::get('lista-auspiciadores',[AuspiciadorController::class, 'listaAuspiciadores'])->name('lista-auspiciadores');
    Route::post('detallar-evento/{id}',[EventoController::class, 'guardarCaracteristicasEvento'])->name('detallar-evento');
    Route::get('lista-facilitadores',[RolPersonaController::class, 'listaFacilitadores'])->name('lista-facilitadores');
    Route::post('guardar-etapa/{id}', [EtapaController::class, 'guardarEtapa'])->name('guardar-etapa');
    Route::get('lista-ubicaciones',[UbicacionController::class, 'listaUbicaciones'])->name('lista-ubicaciones');
    Route::get('lista-tipo-eventos',[TipoEventoController::class, 'listaTipoEventos'])->name('lista-tipo-eventos');
    Route::put('actualizar-participante/{id}',[PersonaController::class, 'actualizarCaracteristicas'])->name('actualizar-participante');
    Route::post('guardar-coach',[PersonaController::class, 'guardarCoach'])->name('guardar-coach');
    Route::get('eventos-eliminables', [EventoController::class, 'listaEliminables'])->name('eventos-eliminables');
    Route::get('eventos-con-inscritos', [EventoController::class, 'listaReporteInscritosEvento'])->name('eventos-con-inscritos');
    Route::get('inscritos-evento/{id}', [InscripcionController::class, 'listaInscritosEvento'])->name('inscritos-evento');
    Route::get('evento-con-etapas/{id}', [EventoController::class, 'tieneEtapas'])->name('evento-con-etapas');
    Route::get('evento-con-detalles/{id}', [EventoController::class, 'tieneDetalles'])->name('evento-con-detalles');
    Route::get('reporte-eventos', [EventoController::class, 'reporteEventos'])->name('reporte-eventos');
    Route::get('lista-usuarios',[UsuarioController::class, 'listaUsuarios'])->name('lista-usuarios');
    Route::get('lista-roles',[RolesController::class, 'listaRoles'])->name('lista-roles');
    Route::post('roles-actualizar-tareas', [RolesController::class, 'actualizarTareas'])->name('roles-actualizar-tareas');
    Route::post('usuarios-actualizar-roles', [UsuarioController::class, 'asignarRol'])->name('usuarios-actualizar-roles');
    Route::get('lista-tareas',[TareaController::class, 'listaTareas'])->name('lista-tareas');
    Route::get('lista-roles-tareas',[RolesController::class, 'listaRolesTareas'])->name('lista-roles-tareas');
    Route::post('crear-usuario', [UsuarioController::class, 'crearUsuario'])->name('crear-usuario');
    Route::get('tareas_de_usuario/{id}', [UsuarioController::class, 'tareasDeUsuario'])->name('tareas_de_usuario');
    Route::get('roles_de_usuario/{id}', [UsuarioController::class, 'rolesDeUsuario'])->name('roles_de_usuario');
    Route::get('participantes-por-genero/{id}', [InscripcionController::class, 'participantesPorGenero'])->name('participantes-por-genero');
});

Route::post('login-usuario', [UsuarioController::class, 'login']);
Route::get('lista-evento-detallado', [EventoController::class, 'listaEventoDetallado']);
Route::post('inscribir-equipo', [InscripcionController::class, 'inscribirEquipo']);
Route::post('inscribir-individual', [InscripcionController::class, 'inscribirEstudiante']);
Route::post('guardar-participante', [PersonaController::class, 'guardarEstudiante']);
Route::get('lista-participantes', [PersonaController::class, 'listParticipantes']);
Route::post('guardar-equipo', [EquipoController::class, 'store']);
Route::get('lista-coach', [RolPersonaController::class, 'listaCoach']);
Route::get('lista-coach-institucion', [RolPersonaController::class, 'listaCoachInstitucion']);
Route::post('login-usuario', [UsuarioController::class, 'login']);
Route::post('enviar-notificacion', [EventoController::class, 'enviarNotificacion']);
Route::post('enviar-codigo-verificacion', [CodigosVerificacionController::class, 'generarYEnviarCodigo']);
Route::post('confirmar-codigo-verificacion', [CodigosVerificacionController::class, 'confirmarCodigo']);
Route::get('lista-participantes-institucion', [PersonaController::class, 'listParticipantesInstitucion']);
Route::get('lista-instituciones', [InstitucionController::class, 'listaInstitucion']);
